Improve collision detection mechanism.
vadim94/platformer pull request #18
Opened 2017-07-23 06:45 UTC by ioan994

Reset only vertical/horizontal component speed vector depending on how object collides.

2017-07-23 10:32 UTC, vadim94 requested changes

2017-07-23 10:32 UTC, vadim94 commented on platformerLib/GameEngine.cpp
> +   bool is_touched_horizontally = false;
Incorrect indents here and below.
Can't be submitted to master :(

2017-07-23 19:23 UTC, ioan994 commented on platformerLib/GameEngine.cpp
> +   bool is_touched_horizontally = false;
We are going to use spaces, aren't we?

2017-07-23 20:34 UTC, vadim94 commented on platformerLib/GameEngine.cpp
> +   bool is_touched_horizontally = false;
Yes, but we shouldn't leave both spaces and tabs in the source file (it looks ugly).
Please, make the same style in the whole file.

2017-08-07 20:17 UTC, ioan994 commented
Updated formatting

2017-08-07 20:40 UTC, merged